name: Flutter Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - uses: subosito/flutter-action@v2  # Updated to v2
        with:
          flutter-version: '3.13.0'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
